### ISSUE TITLE
4. 기능 수정

### ISSUE THREAD

**Issue by YueunKim** [woorifisa-service-dev-2nd/frontend-1th-RSP_Go#13]
- 사람 추가 4명까지만 가능하도록 수정
- 가위 바위 보 선택 안하고 결과 보기 클릭 시 선택하라는 문장 출력하도록 수정
- 이미지 크기 조정, 선택 박스 오른쪽 마진 추가
- 제목 폰트 적용

**Comment by KyuliLee** [comment]
👍
